### ISSUE TITLE
hello ,this weekend i will come to beijing to attend a meeting from US, could we hava a short talking this weekend, I will pay for the coffe,i don't know if you are busy,looking forward to you response!

### ISSUE THREAD

**Issue by zac7070** [haiker2011/awesome-nlp-sentiment-analysis#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by haiker2011** [comment]
不好意思，我英文水平有限，使用中文简单回答一下吧。

1. 我主要研究的问题是热点新闻的评论中评价对象和评价词的抽取，现在很多这方面的研究还主要集中在产品和影评，对新闻评论关注不够。对于新闻评论分析评价对象和评价词可以掌握对一个热点新闻大众的看法，有利于进一步的决策。
2. 当前的研究中中文评论评价对象和评价词抽取缺少高质量数据集，对于开展工作很不利，计划构建一个相对大的数据集，利用新闻评论之间和新闻和评论之间的关系进行半监督学习来处理。第二部分是拥有数据集之后，充分利用新闻正文和同一新闻下面评论之间关系来提高抽取效果。
3. 后续我们还要解决对齐，指代消解等问题，甚至结合同一话题之间的强相互关系来构建知识库。研究结束之后有时间的话会把各个组件微服务化和 Docker 化，提供高可用服务集群。

**Comment by haiker2011** [comment]
@zac7070 不好意思，我英文水平有限，使用中文简单回答一下吧。

1. 我主要研究的问题是热点新闻的评论中评价对象和评价词的抽取，现在很多这方面的研究还主要集中在产品和影评，对新闻评论关注不够。对于新闻评论分析评价对象和评价词可以掌握对一个热点新闻大众的看法，有利于进一步的决策。
2. 当前的研究中中文评论评价对象和评价词抽取缺少高质量数据集，对于开展工作很不利，计划构建一个相对大的数据集，利用新闻评论之间和新闻和评论之间的关系进行半监督学习来处理。第二部分是拥有数据集之后，充分利用新闻正文和同一新闻下面评论之间关系来提高抽取效果。
3. 后续我们还要解决对齐，指代消解等问题，甚至结合同一话题之间的强相互关系来构建知识库。研究结束之后有时间的话会把各个组件微服务化和 Docker 化，提供高可用服务集群。
